### ISSUE TITLE
LRS Table Issue

### ISSUE THREAD

**Issue by mikedawson** [UstadMobile/UstadMobile#27]
After restarting the app a few times the app makes a request to check for resumable statements:

http://localhost:8425/xAPI/statements?agent=%7B%22account%22%3A%7B%22homePage%22%3A%22http%3A%5C%2F%5C%2Fumcloud1.ustadmobile.com%5C%2Fumlrs%5C%2F%22%2C%22name%22%3A%22medteacher2%22%7D%2C%22objectType%22%3A%22Agent%22%7D&activity=epub%3A31daeq7-617d-402e-a0b0-dba52ef21911

Receives the response:

04-19 18:03:41.352 25464-26937/com.toughra.ustadmobile E/UMLogAndroid: 192 : no such table: cache_statement_list
                                                                       org.json.JSONException: Value no of type java.lang.String cannot be converted to JSONObject
                                                                           at org.json.JSON.typeMismatch(JSON.java:111)
                                                                           at org.json.JSONObject.<init>(JSONObject.java:160)
                                                                           at org.json.JSONObject.<init>(JSONObject.java:173)
                                                                           at com.ustadmobile.core.util.UMTinCanUtil.getStatementsFromResult(UMTinCanUtil.java:263)
                                                                           at com.ustadmobile.port.android.impl.UstadMobileSystemImplAndroid$4.run(UstadMobileSystemImplAndroid.java:845)
                                                                           at java.lang.Thread.run(Thread.java:818)

**Comment by mikedawson** [comment]
This is now obsolete with removing embedded Django and switching to SQLite NanoLRS
