### ISSUE TITLE
Android NsdManager crashes with NullPointerException

### ISSUE THREAD

**Issue by mikedawson** [UstadMobile/UstadMobile#42]
Android NsdManager on older versions of Android is unstable as per:

https://issuetracker.google.com/issues/36952181

This can lead to a NullPointerException being thrown : 

```
08-10 13:43:39.623 6188-6223/? E/AndroidRuntime: FATAL EXCEPTION: NsdManager
                                                 Process: com.toughra.ustadmobile.uswdp, PID: 6188
                                                 java.lang.NullPointerException
                                                     at android.net.nsd.NsdManager$ServiceHandler.handleMessage(NsdManager.java:337)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
```

Unfortunately with the state of NsdManager on Android there's not much we can do about it. On Android versions < 6 we could use JmDns instead. JmDns is stable but requires a unicast lock (increasing battery usage).

**Comment by mikedawson** [comment]
Workaround implemented in commit 3a84678 + commit 3d26faf . JmDns is now used by default on Android < version 5.
