### ISSUE TITLE
Crash caused by null p2p service info.

### ISSUE THREAD

**Issue by mikedawson** [UstadMobile/UstadMobile#51]
Issue caused apparently by serviceinfo.newinstance returning null. Todo: add a try/catch statement when calling add localservice, if an exception is thrown, call onFailure.

09-06 08:58:18.084 1673-1673/com.toughra.ustadmobile.uswdp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: com.toughra.ustadmobile.uswdp, PID: 1673
                                                                             java.lang.IllegalArgumentException: service info is null
                                                                                 at android.net.wifi.p2p.WifiP2pManager.checkServiceInfo(WifiP2pManager.java:862)
                                                                                 at android.net.wifi.p2p.WifiP2pManager.addLocalService(WifiP2pManager.java:1090)
                                                                                 at edu.rit.se.wifibuddy.WifiDirectHandler$2.onSuccess(WifiDirectHandler.java:431)
                                                                                 at android.net.wifi.p2p.WifiP2pManager$Channel$P2pHandler.handleMessage(WifiP2pManager.java:748)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
09-06 08:58:18.097 2124-21911/? W/ActivityManager:   Force finishing activity com.toughra.ustadmobile.uswdp/com.ustadmobile.port.android.view.BasePointActivity
09-06 08:58:18.104 2124-21911/? D/ActivityTrigger: ActivityTrigger activityPauseTrigger 
09-06 08:58:18.133 2124-2180/? V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@6a8bd14
09-06 08:58:18.133 2124-2180/? V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@ecc9bd
09-06 08:58:18.138 2124-2180/? V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@3de9680
09-06 08:58:18.138 2124-2180/? V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@ea144b9
09-06 08:58:18.184 2124-6171/? I/OpenGLRenderer: Initialized EGL, version 1.4

**Comment by mikedawson** [comment]
This was caused by an issue in WiFi Buddy. When wifi was disabled, any local service would be cleared. Wifip2pserviceinfo was set to null in the onSuccess handler. When wifi is enabled, a local service would be added. It first called clearLocalServices. Thus what could happen is wifi disabled - remove local service - wifi enabled - clearLocalServices - remove local service onSuccess (sets serviceinfo to null), then addLocalService (which attempts to add a null service).

Fixed with commit 3a84678 and commit 3d26faf along with change to WiFi Buddy. WiFi Buddy now maintains an async queue to prevent the possibility of tasks running in the wrong order.
