### ISSUE TITLE
android-job random JobScheduler null exception on JobStatus.getUid()

### ISSUE THREAD

**Issue by varunasingh** [UstadMobile/UstadMobile#52]
Similar to AOSP issue: https://issuetracker.google.com/issues/37018640

Also mentioned in library: https://github.com/evernote/android-job/issues/92

E/AndroidRuntime( 6936): java.lang.NullPointerException: Attempt to invoke virtual method 'int com.android.server.job.controllers.JobStatus.getUid()' on a null object reference 
E/AndroidRuntime( 6936):    at android.os.Parcel.readException(Parcel.java:1546) 
E/AndroidRuntime( 6936):    at android.os.Parcel.readException(Parcel.java:1493) 
E/AndroidRuntime( 6936):    at android.app.job.IJobCallback$Stub$Proxy.jobFinished(IJobCallback.java:167) 
E/AndroidRuntime( 6936):    at android.app.job.JobService$JobHandler.handleMessage(JobService.java:147) 
E/AndroidRuntime( 6936):    at android.os.Handler.dispatchMessage(Handler.java:102) 
E/AndroidRuntime( 6936):    at android.os.Looper.loop(Looper.java:135) 
E/AndroidRuntime( 6936):    at android.app.ActivityThread.main(ActivityThread.java:5312) 
E/AndroidRuntime( 6936):    at java.lang.reflect.Method.invoke(Native Method) 
E/AndroidRuntime( 6936):    at java.lang.reflect.Method.invoke(Method.java:372) 
E/AndroidRuntime( 6936):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901) 
E/AndroidRuntime( 6936):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696) 

App was closed. JobScheduler did its thing and crashed leading to "This app has crashed" dialog box on the phone/tablet. Problem first seen on Lenovo Yoga tablet Android 7

**Comment by mikedawson** [comment]
Exception observed on Yoga Tablet 2 Pro (Android 5.1):
```
09-06 18:44:12.059 9084-13757/com.ustadmobile.testslave I/JobExecutor: Finished job{id=61, finished=true, result=SUCCESS, canceled=false, periodic=true, class=UMSyncJob, tag=umsync_job_tag}
09-06 18:44:12.059 9084-9084/com.ustadmobile.testslave E/JobService: Application unable to handle onStopJob.
                                                                     java.lang.NullPointerException: Attempt to invoke virtual method 'int com.android.server.job.controllers.JobStatus.getUid()' on a null object reference
                                                                         at android.os.Parcel.readException(Parcel.java:1546)
                                                                         at android.os.Parcel.readException(Parcel.java:1493)
                                                                         at android.app.job.IJobCallback$Stub$Proxy.acknowledgeStopMessage(IJobCallback.java:144)
                                                                         at android.app.job.JobService$JobHandler.ackStopMessage(JobService.java:183)
                                                                         at android.app.job.JobService$JobHandler.handleMessage(JobService.java:136)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:135)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5306)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
09-06 18:44:12.059 9084-9084/com.ustadmobile.testslave D/AndroidRuntime: Shutting down VM
09-06 18:44:12.059 9084-9084/com.ustadmobile.testslave E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: com.ustadmobile.testslave, PID: 9084
                                                                         java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.android.server.job.controllers.JobStatus.getUid()' on a null object reference
                                                                             at android.app.job.JobService$JobHandler.handleMessage(JobService.java:139)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:135)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5306)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
                                                                          Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.android.server.job.controllers.JobStatus.getUid()' on a null object reference
                                                                             at android.os.Parcel.readException(Parcel.java:1546)
                                                                             at android.os.Parcel.readException(Parcel.java:1493)
                                                                             at android.app.job.IJobCallback$Stub$Proxy.acknowledgeStopMessage(IJobCallback.java:144)
                                                                             at android.app.job.JobService$JobHandler.ackStopMessage(JobService.java:183)
                                                                             at android.app.job.JobService$JobHandler.handleMessage(JobService.java:136)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:135) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5306) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694) 
```

**Comment by varunasingh** [comment]
Will wait for this to come up with recent fixes with the way jobs are assigned. Closing but if it comes up, it will get re opened.

**Comment by nayan-dhabarde** [comment]
@mikedawson Can you please explain how does you commit fix the above issue?

**Comment by mikedawson** [comment]
> 
It doesn't . I think this issue is obsolete and refers to a 5 year old version of WorkManager. GitHub mistakenly connected Issue 52 and pull request 52.
